### ISSUE TITLE
Prevent Unmonitoring

### ISSUE THREAD

**Issue by elit3ge** [Vansmak/OCDarr#1]
Once an episode has been watched, is there a way to prevent the episode from being unmonitored?

**Comment by Vansmak** [comment]
Can add that, I built this with my own habits in mind and I just dont see the point in monitoring something I won't watch again. I'll add it as an option.

**Comment by Vansmak** [comment]
added monitor_watched true or false

**Comment by elit3ge** [comment]
Getting this error now.

```2024-05-11 21:22:01,887 - DEBUG - IDs to unmonitor: [30069, 30070, 30071, 30072, 30073, 30085, 32638, 32639]

Traceback (most recent call last):

  File "/app/servertosonarr.py", line 214, in <module>

    main()

  File "/app/servertosonarr.py", line 184, in main

    keep_ids = determine_keep_ids(current_season_episodes, episode_number, config['KEEP_WATCHED'], config['ALWAYS_KEEP'])

KeyError: 'KEEP_WATCHED'
```

**Comment by Vansmak** [comment]
should be fixed now.  Are you building it with compose or using the prebuilt docker image?

**Comment by elit3ge** [comment]
Prebuilt docker image, I was building it myself before you made one.
