### ISSUE TITLE
Add Show

### ISSUE THREAD

**Issue by elit3ge** [Vansmak/OCDarr#2]
Is there a way to add shows if it's being played and it doesn't exist in Sonarr?

**Comment by Vansmak** [comment]
Could add that but it wouldn't know anything but the title so there could be several mismatches.  I have a version using tautulli I can look into it.

It uses the title to get the series id from sonaŕr and then that's how it knows all the networks about seasons and episodes.

**Comment by elit3ge** [comment]
So I have an odd use case, I have multiple instances of Sonarr running.
I'd like to add what's trending to a certain Sonarr instance using this.

**Comment by Vansmak** [comment]
best i could do is in the settings tab of the html it should have a log of and shows that werent matched then a link to sonarr to add them yourself. hard for me to test because all my shows are in one sonarr

**Comment by elit3ge** [comment]
Okay, small teething issue. I have shows in the list via the log but the webui shows nothing.

![image](https://github.com/Vansmak/OCDarr/assets/1644699/e307bc2e-a944-4d26-8aa6-d7aba4904ba2)

**Comment by Vansmak** [comment]
Hmm. I couldn't test it but that gives me an idea. I'll create a dummy one with shows I don't have to see what happens.

**Comment by Vansmak** [comment]
![Settings](https://github.com/Vansmak/OCDarr/assets/16037573/e21493ab-6ace-4457-a992-4892384f1fb1)
give er a try.  heads up, i  wont be able to make one off changes like this going forward.  It still at its core just a tool that was built for my own use cases.   This is good though for me to get experience
