### ISSUE TITLE
prebuilt docker?

### ISSUE THREAD

**Issue by stayupthetree** [Vansmak/OCDarr#3]
Is a prebuilt docker image in the works?

**Comment by Vansmak** [comment]
No plans to. I really don't want to maintain too much and different architectures. Will see

**Comment by Vansmak** [comment]
give it a try https://hub.docker.com/r/vansmak/ocdarr

**Comment by stayupthetree** [comment]
dope! When I get back from my trip I will give it a go! Thank you!

**Comment by Vansmak** [comment]
On docker hub
