### ISSUE TITLE
Weird issue at end of seasons

### ISSUE THREAD

**Issue by stayupthetree** [Vansmak/OCDarr#4]
Everything works great until I get to the end of a season. It will pickup the season switch and download just fine, but it stops removing the watched content from the previous season, it will however start removing from the next season when you keep watching.

{
    "get_option": 1,
    "action_option": "search",
    "keep_watched": 3,
    "monitor_watched": false,
    "always_keep": []
}

![image](https://github.com/Vansmak/OCDarr/assets/239234/02950c43-a617-4127-8a19-46a331704828)

**Comment by Vansmak** [comment]
Good catch.  It isnt coded to look back to the previous season for deleting.  Ill have to look into it.  Thanks

**Comment by Vansmak** [comment]
Ok try it again, works on my end

**Comment by stayupthetree** [comment]
Havent gotten to test the season end/begin just yet..working my way through this series. But finishing the bottom episode and it skipped the last 3 of Season 5 and got the first episode of season 6
![image](https://github.com/Vansmak/OCDarr/assets/239234/f4dae33d-cb63-4b8a-b0fe-c4e90bc66558)

**Comment by Vansmak** [comment]
can you share the logs/app.log? it may be long so you can takes out all the old stuff before this happened.  Thanks.  Also have you updated it recently?  How are you running it prebuilt docker?

**Comment by stayupthetree** [comment]
https://pastebin.com/8aCcrCd3

I updated yesterday

I am using the docker-compose I can switch to the prebuilt if need be.

**Comment by Vansmak** [comment]
I updated it.  My testes seem to be working.  Careful though because it will delete everyting in that series before the amount of episodes you indicate. even previous season.

**Comment by Vansmak** [comment]
> I updated it.  My testes seem to be working.  Careful though because it will delete everyting in that series before the amount of episodes you indicate. even previous season. 

Lmao. I'm leaving this because it's funny. My testes seem to working

**Comment by stayupthetree** [comment]
LOL! Well thats good. Just did some testing. Working as intended now thank you!

Quick thing, 

"keep_watched": 3,", not sure it is being used right? Like right now I should have more than 2 episodes available for the show I am watching, but I only have 2. It's been ongoing but it never clicked that it was set to 3 and I should have more episodes.

**Comment by Vansmak** [comment]
should have 3 including the one just watched.  So if just watched s2e5  there should be e5 e4 and e3.  'Season' would have all back to s2e1.  and 'all' doesnt remove anything.   In theory at least.
