### ISSUE TITLE
Automatically Assign Rule

### ISSUE THREAD

**Issue by elit3ge** [Vansmak/OCDarr#7]
Is it possible to automatically assign a profile to all shows? Before rules came in, it worked great. Now my new shows that are being added aren't being followed.

**Comment by Vansmak** [comment]
Or a default.y es. I'll see too it but strapped for time

**Comment by Vansmak** [comment]
i added a default.  so when you go into rules you will see default, change the parameters to your preferences/  no if no other rule it will do whatever the default is.

**Comment by bettyjames** [comment]
That is brilliant. Thank you!
